package com.shivams.mockmate.model

/**
 * Data models for AI-powered performance insights
 */

/**
 * Represents a comprehensive performance insight generated by AI
 */
data class PerformanceInsight(
    val title: String,
    val summary: String,
    val weakAreas: List<WeakArea>,
    val suggestions: List<ImprovementSuggestion>,
    val motivationalNote: String
)

/**
 * Represents an area where the user needs improvement
 */
data class WeakArea(
    val subject: String,
    val topic: String? = null,
    val accuracy: Float,
    val questionsAttempted: Int
)

/**
 * Represents an improvement suggestion from AI
 */
data class ImprovementSuggestion(
    val area: String,
    val suggestion: String,
    val priority: SuggestionPriority
)

/**
 * Priority level for improvement suggestions
 */
enum class SuggestionPriority { 
    HIGH, 
    MEDIUM, 
    LOW 
}

/**
 * Quick insight for dashboard display
 */
data class QuickInsight(
    val message: String,
    val actionPrompt: String,
    val focusArea: String?
)

/**
 * Test-specific insight after completing a test
 */
data class TestResultInsight(
    val overallFeedback: String,
    val strengths: List<String>,
    val areasToImprove: List<String>,
    val nextSteps: String,
    val encouragement: String
)
